{
    "name": "Custom Company and VAT Label",
    "version": "1.0",
    "category": "Accounting",
    "summary": "Add director field to companies and rename Taxes label to Vat in invoice form",
    "author": "AutoGenerated",
    "depends": ["base", "account"],
    "data": [
        "views/company_view.xml",
        "views/invoice_view.xml"
    ],
    "installable": True,
    "application": False,
    "auto_install": False
}
